### ISSUE TITLE
Checklist for new TOML updates

### ISSUE THREAD

**Issue by ehuss** [alexcrichton/toml-rs#224]
Here is a list of changes to the TOML spec that have not yet been added to toml-rs.

I'm wondering if you would prefer to wait until the spec is finalized to a specific version, or if you would prefer to be proactive in keeping up-to-date.

- [x] Support hex, octal, and binary integer formats ([commit](https://github.com/toml-lang/toml/commit/c69875f7b7d3a764ac8699fbd7915d963a25685c)).
- [x] Support special float values inf and nan, including signs [#506](https://github.com/toml-lang/toml/pull/506).
- [x] Support space instead of T for datetime objects [#501](https://github.com/toml-lang/toml/pull/501).
- [x] Bare U+007f should be rejected from strings [#485](https://github.com/toml-lang/toml/issues/485).  
- [x] Support dotted keys [#505](https://github.com/toml-lang/toml/pull/505).

**Comment by ehuss** [comment]
@alexcrichton Tom [released 0.5 today](https://github.com/toml-lang/toml/releases/tag/v0.5.0), I was wondering if you would be interested in PRs for the new features and changes?

**Comment by alexcrichton** [comment]
I would definitely be interested! If they come with breaking API changes to the `toml` crate I'd be totally down for a major version bump as well

**Comment by ehuss** [comment]
@alexcrichton Hm, I completely forgot about updating the macros until after I pushed.  I will look at supporting them tomorrow, but I often struggle with macros, so it may take a little time.

**Comment by alexcrichton** [comment]
Ah yeah no worries, it's fine to update them as-needed.

**Comment by birkenfeld** [comment]
Should the README be updated to say that 0.5 is (at least partially) now supported?

**Comment by alexcrichton** [comment]
Er oops, yes indeed!
